# Generated by Django 4.2.2 on 2023-07-05 09:06

import bakery_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('accessory_price', models.FloatField(max_length=100)),
                ('about_accessory', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('accessory_Dimension', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('accessory_image1', models.ImageField(upload_to='accessories_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('accessory_image2', models.ImageField(upload_to='accessories_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('accessory_image3', models.ImageField(upload_to='accessories_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_sub_title', models.CharField(max_length=100)),
                ('banner_photo', models.ImageField(upload_to='banner_images/', validators=[bakery_app.models.validate_banner_image])),
            ],
        ),
        migrations.CreateModel(
            name='IntroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='slider_images/', validators=[bakery_app.models.validate_image_dimensions])),
            ],
        ),
    ]
