# Generated by Django 4.2.2 on 2023-07-11 07:17

import bakery_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0002_accessorybanner_cakebanner_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=100)),
                ('banner_sub_title', models.CharField(max_length=100)),
                ('banner_photo', models.ImageField(upload_to='cakebanner_images/', validators=[bakery_app.models.validate_banner_image])),
                ('banner_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='accessoryBanner',
        ),
        migrations.DeleteModel(
            name='cakeBanner',
        ),
    ]
