# Generated by Django 4.2.2 on 2023-07-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0005_cakes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakes',
            old_name='accessory_image1',
            new_name='cake_image1',
        ),
        migrations.RenameField(
            model_name='cakes',
            old_name='accessory_image2',
            new_name='cake_image2',
        ),
        migrations.RenameField(
            model_name='cakes',
            old_name='accessory_image3',
            new_name='cake_image3',
        ),
    ]
