# Generated by Django 4.2.2 on 2023-07-12 06:10

import bakery_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0006_rename_accessory_image1_cakes_cake_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cakeOnSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cake_actial_price', models.FloatField(max_length=100)),
                ('cake_sale_price', models.FloatField(max_length=100)),
                ('about_cake', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('cake_weight', models.CharField(max_length=100)),
                ('cake_toppings', models.CharField(max_length=100)),
                ('cake_extras', models.CharField(max_length=100)),
                ('cake_image1', models.ImageField(upload_to='cakeonsale_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('cake_image2', models.ImageField(upload_to='cakeonsale_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('cake_image3', models.ImageField(upload_to='cakeonsale_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cakes',
            name='cake_image1',
            field=models.ImageField(upload_to='cake_images/', validators=[bakery_app.models.validate_cake_image_dimensions]),
        ),
        migrations.AlterField(
            model_name='cakes',
            name='cake_image2',
            field=models.ImageField(upload_to='cake_images/', validators=[bakery_app.models.validate_cake_image_dimensions]),
        ),
        migrations.AlterField(
            model_name='cakes',
            name='cake_image3',
            field=models.ImageField(upload_to='cake_images/', validators=[bakery_app.models.validate_cake_image_dimensions]),
        ),
    ]
