# Generated by Django 4.2.2 on 2023-07-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0007_cakeonsale_alter_cakes_cake_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakeonsale',
            old_name='cake_actial_price',
            new_name='cake_actual_price',
        ),
    ]
