# Generated by Django 4.2.2 on 2023-07-12 06:51

import bakery_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0008_rename_cake_actial_price_cakeonsale_cake_actual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_story', models.TextField()),
                ('image1', models.ImageField(upload_to='aboutus_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('our_mission', models.TextField()),
                ('image2', models.ImageField(upload_to='aboutus_images/', validators=[bakery_app.models.validate_cake_image_dimensions])),
                ('quote', models.CharField(blank=True, max_length=500, null=True)),
                ('quote_author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
