# Generated by Django 4.2.2 on 2023-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakes',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
