# Generated by Django 4.2.2 on 2023-07-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0011_cakes_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='description',
            field=models.TextField(),
        ),
    ]
