# Generated by Django 4.2.2 on 2023-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0012_alter_cakes_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.CharField(max_length=100)),
                ('client_message', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='contact',
            new_name='contact_info',
        ),
    ]
